# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import preguntales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0024_auto_20160307_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswerIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=preguntales.models.uuid_with_no_dashes, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_identifiers', to='elections.Candidate')),
            ],
        ),
    ]
